### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by g-fb** [wangwenx190/QtMediaPlayer#1]
Trying to compile this on openSUSE Tumbleweed, but compilation fails.
Build commands:
```
 cmake .
 cmake --build .
```
[output](https://pastebin.com/EqRg3KUL)

----
gcc (SUSE Linux) 11.2.1 20220103 [revision d4a1d3c4b377f1d4acb34fe1b55b5088a3f293f6]

Operating System: openSUSE Tumbleweed 20220210
KDE Plasma Version: 5.24.0
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Kernel Version: 5.16.5-1-default (64-bit)
Graphics Platform: X11

**Comment by wangwenx190** [comment]
Sorry for the inconvenience, will fix right away.

**Comment by wangwenx190** [comment]
Well, I tested build with Qt 5.15.2 on Windows, and this issue doesn't  occur. But it's still fixable.

**Comment by wangwenx190** [comment]
This issue should be fixed now, please test the latest code.

**Comment by g-fb** [comment]
Thanks for fixing these.

Still getting a few errors.
If I include cstring `#include <cstring>` it stops complaining about memcpy .

```bash
.../c++/QtMediaPlayer/src/backends/mpv/mpvqthelper.cpp: In member function ‘char* MPV::Qt::node_builder::dup_qstring(const QString&) const’:
.../c++/QtMediaPlayer/src/backends/mpv/mpvqthelper.cpp:522:18: error: ‘memcpy’ is not a member of ‘std’; did you mean ‘wmemcpy’?
  522 |             std::memcpy(r, b.data(), b.size() + 1);
      |                  ^~~~~~
      |                  wmemcpy
.../c++/QtMediaPlayer/src/backends/mpv/mpvqthelper.cpp: At global scope:
.../c++/QtMediaPlayer/src/backends/mpv/mpvqthelper.cpp:778:8: error: ambiguating new declaration of ‘qint64 mpv_client_id(mpv_handle*)’
  778 | qint64 mpv_client_id(mpv_handle *ctx)
      |        ^~~~~~~~~~~~~
In file included from .../c++/QtMediaPlayer/src/backends/mpv/mpvqthelper.h:28,
                 from .../c++/QtMediaPlayer/src/backends/mpv/mpvqthelper.cpp:41:
.../c++/QtMediaPlayer/src/backends/mpv/include/mpv/client.h:423:20: note: old declaration ‘int64_t mpv_client_id(mpv_handle*)’
  423 | MPV_EXPORT int64_t mpv_client_id(mpv_handle *ctx);
      |                    ^~~~~~~~~~~~~
.../c++/QtMediaPlayer/src/backends/mpv/mpvqthelper.cpp:818:8: error: ambiguating new declaration of ‘qint64 mpv_get_time_us(mpv_handle*)’
  818 | qint64 mpv_get_time_us(mpv_handle *ctx)
      |        ^~~~~~~~~~~~~~~
In file included from .../c++/QtMediaPlayer/src/backends/mpv/mpvqthelper.h:28,
                 from .../c++/QtMediaPlayer/src/backends/mpv/mpvqthelper.cpp:41:
.../c++/QtMediaPlayer/src/backends/mpv/include/mpv/client.h:616:20: note: old declaration ‘int64_t mpv_get_time_us(mpv_handle*)’
  616 | MPV_EXPORT int64_t mpv_get_time_us(mpv_handle *ctx);
      |                    ^~~~~~~~~~~~~~~
.../c++/QtMediaPlayer/src/backends/mpv/mpvqthelper.cpp:990:9: error: ambiguating new declaration of ‘quint64 mpv_render_context_update(mpv_render_context*)’
  990 | quint64 mpv_render_context_update(mpv_render_context *ctx)
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from .../c++/QtMediaPlayer/src/backends/mpv/include/mpv/render_gl.h:19,
                 from .../c++/QtMediaPlayer/src/backends/mpv/mpvqthelper.cpp:42:
.../c++/QtMediaPlayer/src/backends/mpv/include/mpv/render.h:660:21: note: old declaration ‘uint64_t mpv_render_context_update(mpv_render_context*)’
  660 | MPV_EXPORT uint64_t mpv_render_context_update(mpv_render_context *ctx);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~
gmake[2]: *** [src/backends/mpv/CMakeFiles/MPVBackend.dir/build.make:118: src/backends/mpv/CMakeFiles/MPVBackend.dir/mpvqthelper.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:274: src/backends/mpv/CMakeFiles/MPVBackend.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
```

**Comment by wangwenx190** [comment]
That's strange. I have never get these errors when compiling. Maybe there's some difference between GCC and MSVC

**Comment by g-fb** [comment]
Any chance the remaining issues will be resolved?

**Comment by wangwenx190** [comment]
Sorry, I thought everything is fixed so I didn't look more into this issue. The error message you pasted here just shows a mismatch of the value types, they are very easy to fix, but the error is strange, `qint64` should be the same with `int64_t`. Can you share your compiler information? maybe your compiler is too old

**Comment by g-fb** [comment]
> Sorry, I thought everything is fixed so I didn't look more into this issue. The error message you pasted here just shows a mismatch of the value types, they are very easy to fix, but the error is strange, `qint64` should be the same with `int64_t`. 

I think the problem is that there are two functions with the same signature, the return type is not part of this signature
https://www.csee.umbc.edu/~chang/cs202.f15/Lectures/modules/m04-overload/slides.php?print

qint64 mpv_client_id(mpv_handle *ctx) in mpvqthelper.cpp
and 
int64_t mpv_client_id(mpv_handle *ctx) in client.h

> Can you share your compiler information? maybe your compiler is too old

gcc (SUSE Linux) 11.2.1 20220103 [revision d4a1d3c4b377f1d4acb34fe1b55b5088a3f293f6]

**Comment by wangwenx190** [comment]
> gcc (SUSE Linux) 11.2.1 20220103

Well, it's quite new

> I think the problem is that there are two functions with the same signature

It should not be a issue because the one in client.h is only a forward declaration.

![图片](https://user-images.githubusercontent.com/17877450/155441518-e2bde59a-844f-4ea4-bbae-ac6d65b669c8.png)

Maybe here is the issue? I heard symbols are exported by default on Linux. Do you know how to un-export a given symbol on Linux?

**Comment by wangwenx190** [comment]
It seems things work quite differently between MSVC and GCC, even though there are two functions with the same signature, one of them is only a forward declaration, the other one is the implementation, there should not be any problem. Or maybe I should add a `extern` to the forward declarations? Can you try it? I'm not familiar with developing on Linux, so I don't quite know how to solve this, really sorry.

**Comment by g-fb** [comment]
> even though there are two functions with the same signature, one of them is only a forward declaration, the other one is the implementation

I don't think that is correct. The implementation of `int64_t mpv_client_id(mpv_handle *ctx)` from client.h is in [client.c](https://github.com/mpv-player/mpv/blob/f9fd50c6546f2fa510251267d6423d3f342ca115/player/client.c#L330)

**Comment by wangwenx190** [comment]
> > even though there are two functions with the same signature, one of them is only a forward declaration, the other one is the implementation
> 
> I don't think that is correct. The implementation of `int64_t mpv_client_id(mpv_handle *ctx)` from client.h is in [client.c](https://github.com/mpv-player/mpv/blob/f9fd50c6546f2fa510251267d6423d3f342ca115/player/client.c#L330)

Yes that's the real and original implementation, but it should not join our compilation process unless you are statically linking against libmpv. So you are linking to libmpv statically? If so, it will cause symbol conflicts indeed. For now, the quickest solution is to link against libmpv dynamically. But I can add a CMake option to this project to avoid such issues, but later.

**Comment by g-fb** [comment]
> So you are linking to libmpv statically?

I don't think I am. My installed mpv library is a dynamic library /usr/lib64/libmpv.so.

**Comment by wangwenx190** [comment]
You can disable the mpv backend temperarily for now, the mdk backend also works well. Just comment out the mpv line in `src/backends/CMakeLists.txt`.
